version: '2.4'

services:

  module:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        IMAGE: ${BASE_IMAGE}
    image: brsynth/${COMPOSE_PROJECT_NAME}
    command: sh -c "
                python3 setup.py sdist bdist_wheel
             && python3 -m twine upload --repository ${TEST}pypi dist/*"
