version: '2.4'

services:

  module:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: sh -c "
                python3 setup.py sdist bdist_wheel
             && python3 -m twine upload --repository ${TEST}pypi dist/*"
